export const SERVICES = [
  {
    "icon": "fa-solid fa-chart-pie",
    "title": "Аналитика и Аудит",
    "description": "Проводим экспертное детальное исследование, выявляем сильные и слабые стороны вашего продукта и предлагаем оптимальные решения.",
    "descriptionRo": "Efectuăm o analiză detaliată și identificăm punctele forte și slabe ale produsului dvs., oferind soluții optime.",
    "descriptionEng": "We perform a detailed expert analysis, identify strengths and weaknesses of your product, and provide optimal solutions.",
    "descriptionFull": "Мы проводим всесторонний анализ вашего продукта, сайта или цифровой платформы, чтобы выявить скрытые проблемы и точки роста. Исследуем технические аспекты, пользовательский опыт, бизнес-логику, маркетинг и конкурентов.\n\nИспользуем комплексный подход: от сбора данных и юзабилити-тестов до анализа метрик, конверсий, скорости и структуры. Всё — на основе проверенных методик, без гаданий и воды.\n\nВы получаете подробный отчёт, где:\n- указаны слабые и сильные стороны текущего решения;\n- даны практические рекомендации по улучшению;\n- составлен roadmap с приоритетами и быстрыми победами (\"quick wins\");\n- есть техническое заключение, если продукт нужно дорабатывать или масштабировать.\n\nНаш аудит подойдёт:\n- компаниям перед редизайном или перезапуском сайта;\n- стартапам, которым важно получить взгляд со стороны до инвестиций;\n- бизнесам, у которых есть трафик, но нет продаж;\n- проектам, где «что-то не так», но непонятно что именно.\n\nРезультат — не просто PDF. Это стратегический документ, который помогает принимать правильные решения и экономить ресурсы. И да, мы не только укажем на проблемы, но и предложим варианты их решения: с цифрами, приоритетами и примерами.",
    "descriptionFullRo": "Efectuăm o analiză completă a produsului, site-ului sau platformei dvs. digitale, pentru a descoperi probleme ascunse și puncte de creștere.\n\nAnalizăm aspectele tehnice, experiența utilizatorului (UX), logica de afaceri, strategia de marketing și concurența. Nu oferim doar păreri — ci un audit profesionist bazat pe date reale, teste, metrici și metodologii dovedite.\n\nVeți primi un raport detaliat care conține:\n- punctele tari și punctele slabe ale produsului actual;\n- recomandări clare pentru îmbunătățiri;\n- un plan de acțiune structurat, cu priorități și pași concreți;\n- concluzii tehnice, utile pentru scalare sau refactorizare.\n\nAuditul nostru este ideal pentru:\n- companii care se pregătesc de redesign sau relansare;\n- startupuri înainte de investiții sau lansare;\n- afaceri care atrag trafic dar nu convertesc;\n- proiecte unde “ceva nu funcționează” și nu e clar ce anume.\n\nRezultatul nu este doar un PDF, ci o hartă strategică a următorilor pași. Economisiți bani, timp și stres — cu o imagine clară asupra direcției în care merită să mergeți.",
    "descriptionFullEng": "We deliver a comprehensive analysis of your product, website, or digital platform — going beyond the surface to uncover hidden issues and growth opportunities.\n\nOur team evaluates the technical foundation, UX/UI, business logic, marketing flow, and competition. We rely on real data, proven methods, and user behavior — not assumptions.\n\nYou'll receive a detailed report that includes:\n- Strengths and weaknesses of your current implementation;\n- Actionable improvement suggestions (technical, UX, business);\n- A prioritized roadmap with quick wins and long-term goals;\n- Technical recommendations for refactoring or scaling.\n\nThis service is ideal for:\n- Businesses planning a redesign or relaunch;\n- Startups preparing for launch or investor due diligence;\n- Projects with traffic but poor conversion;\n- Teams that feel “something is wrong” but can’t pinpoint the issue.\n\nThis isn’t just another document. It’s a strategic decision-making tool that saves time, budget, and nerves. And unlike typical audits, we don’t just diagnose — we provide solutions, prioritization, and examples that work."
  },


  {
    "icon": "fa-solid fa-gears",
    "title": "1С Автоматизация",
    "description": "Интеграция и автоматизация процессов на базе 1С: настройка обмена данными, синхронизация с CRM, ускорение документооборота.",
    "descriptionRo": "Integrarea și automatizarea proceselor în baza 1C: schimb de date, sincronizare cu CRM, accelerarea fluxului de documente.",
    "descriptionEng": "Process automation based on 1C: data exchange, CRM sync, and document workflow acceleration.",
    "descriptionFull": "Автоматизируем и интегрируем процессы с использованием 1С:Предприятие, облегчая рутину и ускоряя операции в компании.\n\nНастраиваем обмен данными между 1С и другими системами: CRM, интернет-магазины, сайты, онлайн-кассы, складские программы, бухгалтерия и логистика. Устраняем “ручной труд” и сводим ошибки к нулю.\n\nМы можем:\n- внедрить синхронизацию с Bitrix24, amoCRM, retailCRM и другими;\n- автоматизировать создание и обмен актами, счетами, заказами, ТТН;\n- подключить обмен по API, FTP, email или напрямую через базу;\n- разрабатывать индивидуальные решения под особенности вашего бизнеса, включая нетиповые механизмы учёта, нестандартную логику документооборота, кастомные обработки и регламентированные отчёты.\n\nРаботает это так:\n1. Анализируем текущую схему бизнес-процессов;\n2. Предлагаем схему автоматизации;\n3. Настраиваем, проверяем, документируем;\n4. Обучаем сотрудников (если нужно);\n5. Сопровождаем и поддерживаем.\n\nВ итоге вы получаете: меньше ручной рутины, выше скорость работы, больше прозрачности и контроль.\nПодходит для компаний любого масштаба — от малого бизнеса до корпораций с уникальными регламентами.\nМы не просто “включаем галочки”, мы разрабатываем решения, которые работают именно под вашу модель бизнеса.",
    "descriptionFullRo": "Automatizăm și integrăm procesele de afaceri cu ajutorul platformei 1C:Enterprise — pentru a reduce rutina manuală și a crește eficiența.\n\nConfigurăm schimbul de date între 1C și alte sisteme: CRM, magazine online, aplicații contabile, sisteme logistice, case de marcat și multe altele.\n\nOferim:\n- sincronizare cu Bitrix24, amoCRM, retailCRM;\n- automatizarea generării actelor, facturilor, comenzilor, TTH;\n- integrare prin API, FTP, email sau conectare directă;\n- dezvoltăm soluții personalizate, inclusiv rapoarte specifice, logici contabile netipice, integrări avansate și module interne create de la zero, pentru nevoile reale ale companiei tale.\n\nPașii noștri:\n1. Analizăm procesele existente;\n2. Propunem soluția optimă de automatizare;\n3. Implementăm și testăm;\n4. Instruiți angajații (opțional);\n5. Oferim suport post-implementare.\n\nRezultatul: mai puține greșeli, procese rapide și o imagine clară asupra activității companiei.\nNu doar implementare — ci dezvoltare reală, adaptată la regulile, echipa și ritmul firmei tale.",
    "descriptionFullEng": "We automate and integrate business operations using the 1C:Enterprise platform to reduce manual work and boost efficiency.\n\nWe set up data synchronization between 1C and other systems — CRM platforms, e-commerce, accounting, POS, logistics, and more.\n\nWe offer:\n- CRM integration (Bitrix24, amoCRM, retailCRM);\n- Automated generation of invoices, orders, acts, and shipments;\n- API, FTP, email or direct database exchange;\n- Custom-developed modules tailored to your business processes — including complex reporting logic, unique accounting flows, and fully bespoke automation pipelines. We build what your company truly needs — not just configure settings.\n\nOur process:\n1. Analyze your current workflow;\n2. Propose the best automation plan;\n3. Set up, test and document the solution;\n4. Train staff if needed;\n5. Provide long-term support and maintenance.\n\nThe result: fewer errors, faster operations, and full control over your back-office.\nSuitable for businesses of all sizes — especially those with unique requirements that can’t be solved by default modules.\nWe create purpose-built solutions that work exactly how your operations demand."
  },


  {
    "icon": "fa-solid fa-laptop-code",
    "title": "Разработка сайтов",
    "description": "Создаём сайты и веб-приложения, которые становятся частью вашей бизнес‑инфраструктуры. От лендингов и интернет‑магазинов до сложных интерфейсов.",
    "descriptionRo": "Creăm site-uri și aplicații web — de la landing page-uri și magazine, până la interfețe complexe integrate în infrastructura afacerii.",
    "descriptionEng": "We create websites and web apps — from landing pages and stores to complex interfaces embedded in your business infrastructure.",
    "descriptionFull": "Мы создаём сайты и веб-приложения, которые становятся частью цифровой инфраструктуры бизнеса. Это не просто страницы — это рабочие интерфейсы, которые помогают продавать, информировать, обслуживать клиентов и управлять процессами.\n\nПроектируем решения, отталкиваясь от задач. Если нужно — расскажем, уточним, вместе выстроим архитектуру. В процессе мы учитываем не только внешний вид, но и структуру, конверсионные сценарии, масштабируемость, взаимодействие с внутренними системами.\n\nМы создаём:\n- лендинги и промо-страницы, которые вовлекают;\n- сайты с каталогами, фильтрами, личными кабинетами;\n- административные интерфейсы и панели управления;\n- интеграции с CRM, ERP, платёжными и внешними сервисами.\n\nВсе решения подбираются и реализуются индивидуально, исходя из специфики вашего продукта и процессов. Мы не используем шаблоны — мы строим цифровой продукт, который работает в паре с вашим бизнесом.\n\nТакой подход позволяет запускать не просто “ещё один сайт”, а создать надёжную основу для роста, автоматизации и коммуникации с клиентами.",
    "descriptionFullRo": "Creăm site-uri și aplicații web care devin parte din infrastructura digitală a afacerii tale. Nu sunt doar pagini frumoase — sunt interfețe funcționale care vând, informează, gestionează clienți și susțin procesele interne.\n\nAbordăm fiecare proiect în funcție de obiectivele reale. Discutăm, analizăm, construim o arhitectură clară. Punem accent pe logică, scalabilitate, conversie și integrarea cu sistemele existente.\n\nDezvoltăm:\n- pagini de prezentare și promo care atrag;\n- site-uri cu cataloage, filtre și conturi personale;\n- interfețe administrative și panouri de control;\n- integrare cu CRM, ERP, plăți și servicii externe.\n\nToate soluțiile sunt adaptate pentru specificul afacerii tale. Nu folosim șabloane — ci construim un produs digital care lucrează alături de echipa și strategia ta.\n\nAsta înseamnă mai mult decât un simplu site: este o bază stabilă pentru creștere, automatizare și relația cu clienții.",
    "descriptionFullEng": "We create websites and web applications that become a core part of your business’s digital infrastructure. These aren’t just pages — they’re functional interfaces that help sell, inform, support customers, and streamline internal operations.\n\nEvery project begins with understanding your goals. We clarify requirements, help define architecture, and focus on what truly matters — logic, usability, scalability, and integration with your existing systems.\n\nWe build:\n- landing and promo pages that engage;\n- catalog-based sites with filters and user accounts;\n- internal dashboards and admin panels;\n- integrations with CRMs, ERPs, payments, and third-party tools.\n\nEach solution is fully tailored to your business. No templates, no shortcuts — just systems that work hand-in-hand with your processes and long-term vision.\n\nIt's not “just a website” — it's a foundation for growth, automation, and meaningful digital interaction."
  },

  {
    "icon": "fa-brands fa-figma",
    "title": "Web-Дизайн",
    "description": "Создаём UX‑дизайн, который делает интерфейсы понятными, логичными и приятными в использовании. От лендингов и мобильных экранов до сложных B2B‑систем и личных кабинетов.",
    "descriptionRo": "Creăm design UX care face interfețele intuitive, clare și plăcute în utilizare. De la landing page-uri și e-commerce până la panouri B2B și aplicații complexe.",
    "descriptionEng": "We create UX design that makes interfaces intuitive, logical, and pleasant to use. From landing pages and e-commerce to B2B dashboards and complex web apps.",
    "descriptionFull": "Мы подходим к дизайну не как к «оформлению», а как к продуманной системе, которая помогает пользователю быстро понять, что делать — и делает это взаимодействие приятным.\n\nКаждый проект начинается с живого общения с вами. Мы обсуждаем цели, целевую аудиторию, стиль бренда, ваши предпочтения и примеры, которые вам близки. Дизайнер остаётся в постоянном контакте — предлагает варианты, показывает промежуточные решения и объясняет каждое принятое решение.\n\nЧто мы делаем:\n- проектируем UX: структуру, сценарии и логику взаимодействия;\n- создаём UI: визуальную часть, типографику, цветовую гамму и общий стиль;\n- отрисовываем адаптивные макеты под все устройства;\n- подготавливаем готовые прототипы и передаём их в разработку.\n\nМы не используем готовые шаблоны. Каждый дизайн строится под конкретную задачу, отрасль и вашу аудиторию. Для комплексных проектов проводим аудит интерфейсов, выявляем болевые точки пользователей и предлагаем решения.\n\nВ результате вы получаете дизайн, продуманный до мелочей и полностью учитывающий специфику вашего бизнеса. Он не просто «красивый» — он удобный, понятный и эффективно выполняет свои функции, помогая вашим клиентам быстро и без ошибок достигать цели.",
    "descriptionFullRo": "Abordăm designul nu ca pe o simplă parte vizuală, ci ca pe o soluție gândită pentru a ghida utilizatorul și a-i face interacțiunea cât mai clară și eficientă.\n\nFiecare proiect începe cu o discuție reală cu tine. Vorbim despre obiective, audiență, stil vizual, preferințe și exemple de referință. Designerul nostru lucrează în contact direct cu tine, prezintă opțiuni, explică deciziile și ajustează în funcție de feedback.\n\nCe livrăm:\n- UX: structură, scenarii, logica interfeței;\n- UI: stil vizual, tipografie, culori și elemente grafice;\n- machete responsive pentru toate dispozitivele;\n- prototipuri pregătite pentru dezvoltare.\n\nNu folosim șabloane. Fiecare design este personalizat în funcție de domeniul și nevoile afacerii tale. Pentru proiectele mai complexe, analizăm interfețele existente și propunem îmbunătățiri.\n\nRezultatul este un design clar, bine gândit și adaptat realității tale de business — care nu doar arată bine, ci și funcționează perfect pentru utilizatorii tăi.",
    "descriptionFullEng": "We treat design not as decoration, but as a carefully built system that helps users understand and act — quickly, intuitively, and with satisfaction.\n\nEvery project starts with real conversations. We discuss your goals, audience, brand style, preferences, and examples you like. Our designer stays in direct contact, offering options, showing drafts, and explaining every design choice.\n\nWe deliver:\n- UX: structure, logic, and user journeys;\n- UI: visual style, typography, color, and layout;\n- responsive layouts for all devices;\n- clickable prototypes ready for development.\n\nWe don’t use templates. Every design is tailored to your specific product, industry, and users. For complex projects, we analyze existing interfaces, identify weak points, and propose clear improvements.\n\nThe result is a design built with logic and care, fully aligned with your business. It’s not just beautiful — it’s effective, user-friendly, and created to help your customers act confidently and with ease."
  },

  {
    "icon": "fa-solid fa-mobile-screen-button",
    "title": "Мобильная разработка",
    "description": "Создаём мобильные приложения, которые удобно использовать и легко поддерживать. От Telegram и PWA до полноценных решений под Android и iOS.",
    "descriptionRo": "Creăm aplicații mobile ușor de utilizat și de întreținut — de la Telegram și PWA, până la soluții complete pentru Android și iOS.",
    "descriptionEng": "We build mobile apps that are easy to use and maintain — from Telegram and PWAs to full-featured Android and iOS solutions.",
    "descriptionFull": "Мы создаём мобильные приложения, которые работают стабильно, быстро и приятно — на Android, iOS или в виде PWA и Telegram-приложений.\n\nПеред тем как что‑либо проектировать, мы выясняем: кто пользователь, зачем он будет пользоваться приложением, какие задачи оно должно закрывать.\n\nВесь процесс строится в сотрудничестве: мы обсуждаем сценарии, согласовываем дизайн, показываем прототипы, уточняем детали.\n\nЧто мы делаем:\n- проектируем UX под мобильные паттерны;\n- разрабатываем кроссплатформенные приложения с единым кодом;\n- создаём адаптивные интерфейсы и микровзаимодействия;\n- интегрируем API, пуши, авторизацию, оплату.\n\nМы не просто “пишем приложение” — мы помогаем превратить идею в удобный и живой продукт.\n\nПриложения, которые мы делаем, легко масштабируются, быстро загружаются, не пугают пользователя и выглядят одинаково хорошо на любом устройстве.\n\nЕсли нужно — мы берём на себя поддержку и доработки, чтобы ваш проект не просто вышел в стор, а уверенно жил и развивался.",
    "descriptionFullRo": "Creăm aplicații mobile rapide, stabile și intuitive — pentru Android, iOS, Telegram sau sub formă de PWA.\n\nÎncepem prin a înțelege cine sunt utilizatorii, ce nevoi au și cum aplicația îi poate ajuta. Apoi lucrăm împreună, pas cu pas: discutăm scenariile, validăm designul, construim prototipuri și ajustăm funcționalitatea.\n\nCe oferim:\n- UX special gândit pentru mobil;\n- aplicații cross-platform cu cod unificat;\n- interfețe responsive și micro-interacțiuni intuitive;\n- integrare cu API, plăți, autentificare, notificări.\n\nNu „scriem cod” pur și simplu — transformăm ideea ta într-un produs real, optimizat pentru utilizator.\n\nAplicațiile noastre se încarcă rapid, rulează fluid și arată excelent pe orice ecran. Iar dacă dorești — putem asigura și mentenanță și dezvoltare continuă.",
    "descriptionFullEng": "We build mobile applications that are fast, stable, and enjoyable to use — whether it’s for Android, iOS, Telegram, or delivered as a PWA.\n\nOur process starts by understanding your users, their goals, and what problems the app is meant to solve. From there, we work closely with you — mapping out flows, refining the design, building prototypes, and polishing functionality.\n\nWhat we deliver:\n- UX designed specifically for mobile;\n- cross-platform development with a unified codebase;\n- responsive UIs and smooth microinteractions;\n- integration with APIs, payments, login systems, and push notifications.\n\nWe don’t just “code an app” — we help turn your idea into a real, usable product.\n\nOur apps load fast, run smoothly, and look great on any device. And if you need it — we’ll continue to support and improve the product after launch."
  },



  {
    "icon": "fa-solid fa-bullhorn",
    "title": "SMM Продвижение",
    "description": "Продвигаем бизнес в соцсетях через стратегию, контент и аналитику. Помогаем брендам расти, вовлекать аудиторию и превращать подписчиков в клиентов.",
    "descriptionRo": "Promovăm afacerea ta în rețelele sociale prin strategie, conținut și analiză. Creștem implicarea publicului și transformăm urmăritorii în clienți.",
    "descriptionEng": "We promote your business on social media through strategy, content, and analytics. We grow audience engagement and turn followers into real clients.",
    "descriptionFull": "Мы подходим к SMM как к инструменту роста и доверия, а не просто ленте с постами. Наша задача — помочь вашему бизнесу говорить с аудиторией понятным и живым языком.\n\nНачинаем с анализа: разбираемся в нише, целевой аудитории, сильных сторонах вашего продукта. Затем выстраиваем стратегию, в которую входят цели, тон коммуникации, рубрики, форматы и визуальный стиль.\n\nЧто входит в работу:\n- стратегия и медиаплан под выбранные платформы;\n- подготовка контента: тексты, креативы, сторис, видео;\n- регулярный постинг с аналитикой и оптимизацией;\n- запуск рекламы на вовлечение, трафик или заявки.\n\nМы гибко подходим к выбору платформ: Instagram, TikTok, Telegram, Facebook, LinkedIn — в зависимости от вашего продукта и аудитории.\n\nГлавное — не просто “присутствовать”, а быть услышанными. Мы поможем выстроить стиль общения, который вызывает доверие, удерживает внимание и подталкивает к действию.\n\nИ да, мы не просто “ведём соцсети” — мы думаем о целях, бизнесе и измеримом результате: охваты, вовлечённость, клики, лиды.",
    "descriptionFullRo": "Privim SMM-ul ca pe un instrument de creștere și încredere, nu doar o succesiune de postări. Scopul nostru este să ajutăm afacerea ta să comunice clar și natural cu publicul.\n\nÎncepem prin analiză: înțelegem nișa, audiența, valorile produsului. Apoi construim o strategie clară: obiective, tonul vocii, rubrici, stil vizual și tipuri de conținut.\n\nCe facem concret:\n- strategie și plan editorial adaptat platformei alese;\n- conținut: texte, vizualuri, stories, video-uri;\n- postări regulate cu analiză și ajustări;\n- reclame targetate pentru engagement, trafic sau conversii.\n\nAlegem platformele în funcție de obiective: Instagram, TikTok, Telegram, Facebook, LinkedIn — acolo unde e publicul tău.\n\nScopul nu e doar să „fim prezenți”, ci să fim remarcați. Te ajutăm să construiești un stil de comunicare care inspiră încredere și duce la acțiune.\n\nȘi da — nu doar administrăm conturi, ci gândim în termeni de rezultate: reach, engagement, click-uri, lead-uri.",
    "descriptionFullEng": "We see SMM as a growth and trust-building tool — not just a sequence of posts. Our goal is to help your business speak clearly and naturally to your audience.\n\nWe start with analysis: understanding your niche, audience, and the strengths of your product. Then we build a strategy: goals, voice, content pillars, visual style, and post types.\n\nWhat we do:\n- strategy and content planning for each platform;\n- content creation: text, visuals, stories, short videos;\n- regular posting with analytics and optimization;\n- targeted ads for engagement, traffic, or conversions.\n\nWe adapt to the right platform for your goals: Instagram, TikTok, Telegram, Facebook, LinkedIn — wherever your audience is.\n\nOur goal is not just to \"be present\", but to be noticed. We help create a communication style that earns trust, keeps attention, and drives action.\n\nAnd no, we don’t just manage social media — we think in terms of results: reach, engagement, clicks, and leads."
  },

  {
    "icon": "fa-solid fa-magnifying-glass",
    "title": "SEO Оптимизация",
    "description": "Помогаем сайту расти в поисковой выдаче: техническая оптимизация, семантика и контент. Строим стратегию, чтобы привлечь органический трафик и новых клиентов.",
    "descriptionRo": "Creștem vizibilitatea site-ului tău în Google: optimizare tehnică, analiză semantică și conținut clar. Construim o strategie durabilă pentru trafic organic și clienți noi.",
    "descriptionEng": "We help your site grow in search results: technical optimization, keyword analysis, and strong content. A long-term strategy to boost organic traffic and gain real clients.",
    "descriptionFull": "SEO — это не магия и не быстрый трюк, а системная работа над сайтом, его структурой и контентом. Мы выстраиваем стратегию, ориентированную на рост позиций и стабильный органический трафик.\n\nРабота начинается с технического аудита: скорость загрузки, мобильная адаптивность, безопасность, индексация. Затем мы анализируем конкурентов и формируем семантическое ядро — список ключевых фраз, по которым ищут ваши услуги.\n\nДалее оптимизируем:\n- структуру сайта и внутренних ссылок,\n- мета‑теги и заголовки,\n- тексты, описания, статьи, FAQ.\n\nМы не просто \"вставляем ключевые слова\", а создаём полезный и понятный контент — как для поисковых систем, так и для реальных людей.\n\nПроводим регулярный мониторинг, отслеживаем рост позиций и корректируем стратегию. В работе используем профессиональные инструменты и делаем прозрачные отчёты.\n\nРезультат — рост органического трафика, больше заявок и улучшение видимости бренда без постоянных затрат на рекламу.",
    "descriptionFullRo": "SEO nu este magie, ci un proces sistematic care implică optimizarea structurii site-ului și a conținutului. Noi construim o strategie orientată spre creșterea pozițiilor și atragerea de trafic organic stabil.\n\nÎncepem cu un audit tehnic: viteză de încărcare, compatibilitate mobilă, securitate, indexare. Analizăm concurența și creăm un nucleu semantic — cuvintele-cheie relevante pentru afacerea ta.\n\nApoi optimizăm:\n- structura și legăturile interne,\n- titlurile și metatag-urile,\n- textele, descrierile, articolele și FAQ-urile.\n\nNu doar „inserăm cuvinte-cheie”, ci construim conținut util și clar — atât pentru motoarele de căutare, cât și pentru vizitatori.\n\nMonitorizăm pozițiile constant și ajustăm strategia în funcție de rezultate. Folosim instrumente profesionale și oferim rapoarte clare.\n\nRezultatul? Mai mult trafic organic, mai multe cereri și o vizibilitate mai bună pentru brand — fără costuri continue de publicitate.",
    "descriptionFullEng": "SEO isn’t a trick — it’s a systematic approach to optimizing your site’s structure and content. We build long-term strategies that help grow search visibility and attract stable organic traffic.\n\nWe start with a full technical audit: loading speed, mobile responsiveness, security, and indexing. Then we analyze your competitors and build a semantic core — the key phrases your audience is searching for.\n\nNext, we optimize:\n- site structure and internal linking,\n- meta tags and headings,\n- on-page texts, descriptions, articles, FAQs.\n\nWe don’t just “insert keywords” — we create useful, readable content for both search engines and real users.\n\nWe continuously monitor your rankings, adjust strategy, and provide transparent reports using professional tools.\n\nThe result: more organic traffic, higher-quality leads, and better brand visibility — all without relying on constant ad spend."
  },


  {
    icon: 'fa-brands fa-telegram',
    title: 'Telegram Mini App',
    description: 'Разрабатываем мини-приложения внутри Telegram: быстрый запуск MVP, кастомная логика, оплата, взаимодействие с ботами.'
  },

  {
    "icon": "fa-solid fa-diagram-project",
    "title": "Интеграции и автоматизация",
    "description": "Соединяем ваши сервисы в единую систему: сайт, CRM, склад, бухгалтерия, маркетинг. Автоматизируем рутину, убираем дубли, ускоряем бизнес‑процессы.",
    "descriptionRo": "Conectăm serviciile tale într-un sistem unitar: site, CRM, depozit, contabilitate, marketing. Automatizăm rutina și accelerăm procesele de business.",
    "descriptionEng": "We connect your services into a single system: website, CRM, inventory, accounting, marketing. We automate routine tasks and speed up your business processes.",
    "descriptionFull": "Мы помогаем бизнесу избавиться от ручных операций и объединяем разрозненные сервисы в единую экосистему.\n\nИнтеграции позволяют:\n- автоматически передавать заказы с сайта в CRM;\n- синхронизировать остатки товаров между складом, 1С и магазином;\n- передавать счета в бухгалтерию без участия менеджера;\n- запускать маркетинговые триггеры после покупки.\n\nМы работаем с API популярных сервисов (CRM, платёжные шлюзы, ERPs, маркетинг‑платформы) и пишем кастомные коннекторы, если готовых решений нет.\n\nНаша задача — не просто “подключить”, а выстроить логичную и устойчивую схему, которая снимает нагрузку с сотрудников и ускоряет работу.\n\nВсе процессы сопровождаются логированием и проверкой, чтобы вы точно знали, что всё работает как нужно.\n\nИтог — бизнес двигается быстрее, а сотрудники больше не тратят время на копипаст и таблицы.",
    "descriptionFullRo": "Te ajutăm să elimini operațiunile manuale și să transformi sistemele izolate într-un ecosistem coerent.\n\nCe putem automatiza:\n- comenzi de pe site trimise automat în CRM;\n- sincronizarea stocurilor între depozit, 1C și magazinul online;\n- trimiterea facturilor în contabilitate fără intervenție umană;\n- declanșarea campaniilor de marketing după achiziție.\n\nLucrăm cu API-uri ale celor mai folosite servicii (CRM, plăți, ERP-uri, platforme de marketing) și dezvoltăm conectori personalizați atunci când este nevoie.\n\nNu ne limităm la „conectare” — construim un sistem fiabil și clar, care reduce efortul echipei și crește viteza de operare.\n\nFiecare proces este monitorizat și înregistrat, ca să ai mereu controlul.\n\nRezultatul? Afacerea se mișcă mai repede, iar echipa ta se concentrează pe lucruri care contează.",
    "descriptionFullEng": "We help eliminate manual work and turn disconnected systems into a unified ecosystem.\n\nWhat we can automate:\n- orders from your website go straight into the CRM;\n- stock levels stay synced between warehouse, 1C, and store;\n- invoices reach accounting with no human input;\n- marketing flows trigger right after purchase.\n\nWe integrate popular APIs (CRMs, payment gateways, ERPs, marketing platforms) and build custom connectors where needed.\n\nOur goal isn’t just to “connect”, but to build a reliable, logical workflow that reduces load on your team and speeds up operations.\n\nEvery process is logged and verified so you always stay in control.\n\nThe result? Your business runs faster, and your team focuses on what really matters."
  },


  {
    "icon": "fa-solid fa-cloud",
    "title": "DevOps и Инфраструктура",
    "description": "Автоматизируем CI/CD, разворачиваем scalable-инфраструктуру в облаке, оптимизируем производительность и надёжность систем.",
    "descriptionRo": "Automatizăm CI/CD, configurăm infrastructură scalabilă în cloud, optimizăm performanța și fiabilitatea sistemelor.",
    "descriptionEng": "We automate CI/CD, deploy scalable infrastructure in the cloud, and optimize system performance and reliability.",
    "descriptionFull": "Мы помогаем продуктам работать быстро, стабильно и без лишней ручной рутины. Если вы устали от нестабильных серверов и ручного деплоя — мы всё автоматизируем.\n\nЧто делаем:\n- автоматизируем CI/CD пайплайны (build, test, deploy);\n- настраиваем облачную инфраструктуру (AWS, GCP, Hetzner);\n- используем Docker, Kubernetes, легковесные подходы;\n- следим за логами, метриками, алертами и безопасностью;\n- внедряем backup и отказоустойчивость;\n- строим инфраструктуру как код (Ansible, Terraform и др.).\n\nМы подбираем оптимальные решения под ваш стек и бюджет: от монолита на VPS до микросервисов в облаке.\n\nРезультат — надёжная система, быстрые релизы и уверенность, что всё работает даже ночью.",
    "descriptionFullRo": "Construim infrastructuri stabile și scalabile, care reduc munca manuală și accelerează livrarea produselor digitale. Dacă ești sătul de servere instabile sau deploy făcut „cu mâna” — te ajutăm să schimbi asta.\n\nCe oferim:\n- CI/CD complet automatizat (build, testare, deploy);\n- infrastructură în cloud (AWS, GCP, Hetzner, DigitalOcean);\n- containere, Docker, Kubernetes, sau soluții ușoare pentru start;\n- loguri, monitorizare, alerte, backup și recovery;\n- IaC (Infrastructure-as-Code) cu Ansible, Terraform etc.\n\nAlegem soluțiile potrivite în funcție de buget și obiective. Poate fi o aplicație monolitică pe un VPS sau o arhitectură distribuită în cloud.\n\nRezultatul? Mai puține erori, mai puțină rutină, deploy rapid și siguranța că totul funcționează chiar și noaptea.",
    "descriptionFullEng": "We build scalable, stable infrastructure that eliminates manual tasks and speeds up delivery. If you're tired of unstable servers and manual deployments — we help fix that.\n\nWhat we offer:\n- fully automated CI/CD (build, test, deploy);\n- infrastructure in the cloud (AWS, GCP, Hetzner, DigitalOcean);\n- containerization (Docker, Kubernetes) or lightweight setups;\n- logging, monitoring, alerts, backups, and recovery;\n- Infrastructure-as-Code (Ansible, Terraform, etc.).\n\nWe tailor solutions to your budget and product goals — from monolith apps on VPS to distributed microservices.\n\nThe result? Fewer errors, less manual work, faster releases, and peace of mind that everything just works — even at 3AM."
  }


];
